export const initialProducts = [
  {
    name: 'Vitamin C Brightening Serum',
    brand: 'Aurea',
    category: 'Serum',
    price: 1299,
    discountPrice: 999,
    rating: 4.7,
    reviewCount: 214,
    shadeCount: 0,
    concerns: ['Brightening', 'Anti-Aging'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    shades: [],
    description: 'A potent 15% Vitamin C serum that visibly brightens, evens skin tone, and protects against oxidative stress.',
    ingredients: 'Ascorbic Acid 15%, Niacinamide 5%, Ferulic Acid, Hyaluronic Acid, Vitamin E, Green Tea Extract.',
    howToUse: 'Apply 3-4 drops to clean, dry skin every morning. Follow with moisturiser and SPF.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Hydra Boost Moisturiser',
    brand: 'Lumière',
    category: 'Moisturizer',
    price: 899,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 178,
    shadeCount: 0,
    concerns: ['Hydration'],
    skinTypes: ['Dry', 'Combination', 'Sensitive'],
    shades: [],
    description: 'Lightweight gel-cream that delivers 72-hour hydration with no greasy residue.',
    ingredients: 'Hyaluronic Acid, Ceramides, Glycerin, Squalane, Aloe Vera, Panthenol.',
    howToUse: 'Apply liberally to face and neck morning and evening after serum.',
    images: ['https://images.unsplash.com/photo-1608248597022-d4448f0710ab?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Gentle Foam Cleanser',
    brand: 'Veil',
    category: 'Cleanser',
    price: 599,
    discountPrice: 499,
    rating: 4.6,
    reviewCount: 312,
    shadeCount: 0,
    concerns: ['Acne', 'Hydration'],
    skinTypes: ['Oily', 'Combination', 'Sensitive'],
    shades: [],
    description: 'A soap-free foaming cleanser that removes impurities while maintaining the skin barrier.',
    ingredients: 'Cocamidopropyl Betaine, Glycerin, Centella Asiatica, Ceramide NP, Allantoin.',
    howToUse: 'Wet face, apply a small amount, massage gently for 30 seconds, rinse thoroughly.',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'SPF 50+ Invisible Sunscreen',
    brand: 'Aurea',
    category: 'Sunscreen',
    price: 799,
    discountPrice: null,
    rating: 4.8,
    reviewCount: 425,
    shadeCount: 3,
    concerns: ['SPF', 'Brightening'],
    skinTypes: ['Oily', 'Dry', 'Combination', 'Sensitive', 'Normal'],
    shades: [
      { name: 'Translucent', hex: '#f0ede8' },
      { name: 'Ivory', hex: '#e8dfd3' },
      { name: 'Sand', hex: '#d4c4b0' },
    ],
    description: 'Broad-spectrum SPF 50+ with a weightless, non-white-cast formula that sits beautifully under makeup.',
    ingredients: 'Zinc Oxide 12%, Titanium Dioxide 8%, Niacinamide, Dimethicone, Tocopheryl Acetate.',
    howToUse: 'Apply generously as the last step of your morning routine. Reapply every 2 hours.',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Retinol Night Repair Cream',
    brand: 'Dewdrop',
    category: 'Moisturizer',
    price: 1499,
    discountPrice: 1199,
    rating: 4.4,
    reviewCount: 98,
    shadeCount: 0,
    concerns: ['Anti-Aging', 'Brightening'],
    skinTypes: ['Dry', 'Normal', 'Combination'],
    shades: [],
    description: 'A 0.3% retinol formula encapsulated for stability and slow release, reducing fine lines overnight.',
    ingredients: 'Encapsulated Retinol 0.3%, Peptides, Ceramides, Shea Butter, Bisabolol.',
    howToUse: 'Apply a pea-sized amount to face and neck at night. Start 2-3x per week, gradually increase.',
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Salicylic Acid Toner',
    brand: 'Bare Skin',
    category: 'Toner',
    price: 649,
    discountPrice: null,
    rating: 4.3,
    reviewCount: 156,
    shadeCount: 0,
    concerns: ['Acne'],
    skinTypes: ['Oily', 'Combination'],
    shades: [],
    description: '2% Salicylic Acid toner that unclogs pores, reduces blackheads, and refines skin texture.',
    ingredients: 'Salicylic Acid 2%, Witch Hazel, Niacinamide 2%, Green Tea Extract, Allantoin.',
    howToUse: 'After cleansing, apply to cotton pad and sweep across face. Avoid eye area. Use AM or PM.',
    images: ['https://images.unsplash.com/photo-1608248597359-052a58b991ef?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Hyaluronic Acid Hydrating Serum',
    brand: 'Lumière',
    category: 'Serum',
    price: 999,
    discountPrice: 849,
    rating: 4.9,
    reviewCount: 387,
    shadeCount: 0,
    concerns: ['Hydration'],
    skinTypes: ['Dry', 'Sensitive', 'Normal', 'Combination'],
    shades: [],
    description: 'Triple-weight hyaluronic acid that plumps, smooths, and deeply hydrates all skin types.',
    ingredients: 'Hyaluronic Acid (3 molecular weights), Ceramides, Provitamin B5, Glycerin.',
    howToUse: 'Apply to damp skin morning and evening before moisturiser.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Kaolin Clay Purifying Mask',
    brand: 'Veil',
    category: 'Mask',
    price: 849,
    discountPrice: null,
    rating: 4.5,
    reviewCount: 132,
    shadeCount: 0,
    concerns: ['Acne', 'Brightening'],
    skinTypes: ['Oily', 'Combination'],
    shades: [],
    description: 'A mineral-rich clay mask that draws out impurities, minimises pores, and leaves skin smooth.',
    ingredients: 'Kaolin Clay, Bentonite, Activated Charcoal, Tea Tree Extract, Centella Asiatica.',
    howToUse: 'Apply an even layer to clean face. Leave for 10-15 minutes. Rinse with warm water. Use 1-2x per week.',
    images: ['https://images.unsplash.com/photo-1567928805077-8561d3680e92?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Ceramide Barrier Repair Serum',
    brand: 'Aurea',
    category: 'Serum',
    price: 1799,
    discountPrice: 1499,
    rating: 4.7,
    reviewCount: 89,
    shadeCount: 0,
    concerns: ['Hydration', 'Anti-Aging'],
    skinTypes: ['Dry', 'Sensitive', 'Normal'],
    shades: [],
    description: 'A barrier-restoring serum that repairs the skin\'s protective layer with ceramides, fatty acids, and cholesterol.',
    ingredients: 'Ceramides NP/AP/EOP, Phytosphingosine, Cholesterol, Linoleic Acid, Niacinamide.',
    howToUse: 'Apply 3-4 drops to clean skin morning and evening. Follow with moisturiser.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'AHA BHA Exfoliating Toner',
    brand: 'Bare Skin',
    category: 'Toner',
    price: 749,
    discountPrice: null,
    rating: 4.6,
    reviewCount: 201,
    shadeCount: 0,
    concerns: ['Brightening', 'Acne'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    shades: [],
    description: 'A gentle chemical exfoliant with 5% AHA and 2% BHA that resurfaces, brightens, and unclogs pores.',
    ingredients: 'Glycolic Acid 5%, Salicylic Acid 2%, Lactic Acid, Aloe Vera, Calendula Extract.',
    howToUse: 'Apply to cotton pad, sweep over face after cleansing. PM only. Always use SPF the next morning.',
    images: ['https://images.unsplash.com/photo-1608248597359-052a58b991ef?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Niacinamide 10% + Zinc Serum',
    brand: 'Dewdrop',
    category: 'Serum',
    price: 549,
    discountPrice: 449,
    rating: 4.5,
    reviewCount: 533,
    shadeCount: 0,
    concerns: ['Acne', 'Brightening'],
    skinTypes: ['Oily', 'Combination', 'Sensitive'],
    shades: [],
    description: 'Reduces sebum production, visibly minimises pores, and balances uneven skin tone.',
    ingredients: 'Niacinamide 10%, Zinc PCA 1%, Glycerin, Hyaluronic Acid.',
    howToUse: 'Apply 3-4 drops morning and evening after water-based products.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80'],
  },
  {
    name: 'Squalane Facial Oil',
    brand: 'Lumière',
    category: 'Serum',
    price: 1199,
    discountPrice: null,
    rating: 4.8,
    reviewCount: 162,
    shadeCount: 0,
    concerns: ['Hydration', 'Anti-Aging'],
    skinTypes: ['Dry', 'Sensitive', 'Normal'],
    shades: [],
    description: '100% plant-derived squalane that nourishes, softens, and locks in moisture without clogging pores.',
    ingredients: '100% Squalane (Sugar Cane Derived).',
    howToUse: 'Press 3-5 drops into skin morning and/or evening after serum, before or mixed into moisturiser.',
    images: ['https://images.unsplash.com/photo-1608248597022-d4448f0710ab?w=600&auto=format&fit=crop&q=80'],
  },
];
